name: Generate Test Cases

on:
  repository_dispatch:
    types: [generate-tests]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Test Generator
        uses: actions/checkout@v3

      - name: Checkout Target Repo
        uses: actions/checkout@v3
        with:
          repository: owner/repo-A   # yahan apne dusre service ka repo likho
          ref: ${{ github.event.client_payload.ref }}
          path: target-repo

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate test cases
        run: node src/index.js target-repo/src/inputCode.js

      - name: Run Jest tests
        run: npm test
